<?php
			$_defaultNiche = 'nude'; //default niche MUST exists for this country!!!
			$_lang = array(
				 1 => 'Figyelmeztetés',
				 2 => 'Igen',
				 3 => 'Nem',
				 4 => 'Tovább',
				 5 => 'Lépés',
				 6 => 'Elfogadom',
				 7 => 'OK',
				 8 => '-ig',
				 9 => 'Kérdés',
				 10 => 'Az oldal olyan személyek erotikus képeit tartalmazza, akiket ismerhetsz.',
				 19 => 'Ezek a nők CSAK alkalmi partnert keresnek szexre.',
				 20 => 'Szerencséd van, a férfiak regisztrációja még aktuális',
				 21 => 'Kérjük, válaszolj néhány egyszerű kérdésre, hogy meglássuk, van-e számodra megfelelő partner az oldalunkon',
				 22 => 'Köszönjük.',
				 30 => 'Elmúltál 18 éves?',
				 39 => 'Külső',
				 40 => 'Milyen tipusú test izgat fel téged?',
				 41 => 'Soványabb',
				 42 => 'Átlagos',
				 43 => 'Teltkarcsú',
				 44 => 'Nagy mellek kötelezőek',
				 45 => 'Nagy popsi kötelező',
				 46 => 'Célod',
				 48 => 'Milyen tipusú kapcsolatot keresel?',
				 49 => 'Kérjük, válassz ki legfeljebb 3 lehetőséget',
				 50 => 'Egy éjszakás',
				 51 => 'Több alkalom',
				 52 => 'Rendszeres szex kötetlenül',
				 53 => 'Komoly kapcsolat',
				 54 => 'Házasság',
				 55 => 'Keresett korosztály',
				 56 => 'Melyik korosztály felel meg legjobban?',
				 57 => 'Helység',
				 58 => 'Távolság közte és közted?',
				 59 => '1-5 km távolság a mostani tartózkodási helyemtől',
				 60 => 'Ugyanaz a város',
				 62 => 'Közelben levő városok',
				 64 => 'Ugyanaz az ország',
				 65 => 'Nem számít',
				 70 => 'Ok',
				 71 => 'Tovább',
				 72 => 'Egyetértek',
				 80 => 'Add meg az e-mail cimed, hogy folytasd a regisztrációt',
				 81 => 'Add meg az e-mail cimed',
				 82 => 'Küldd',
				 90 => 'perc és',
				 91 => 'másodperc',
				 92 => 'Pár pillanat...',
				 99 => 'E-mail cím ellenőrzése',
				 100 => 'Eredmény',
				 101 => 'Válaszok elemzése',
				 102 => 'Megtaláljuk a számodra megfelelő szexpartnert',
				 103 => '42 tag van a közeledben',
				 104 => 'Csak 3 szabad hely van a regisztrációhoz',
				 105 => 'Gratulálunk, regisztrálhatsz az oldalra!',
				 106 => 'Szabályaink:',
				 109 => 'Nem találtunk korábbi, hozzád köthető regisztrációt',
				 110 => 'Jelenleg csak',
				 111 => 'regisztrációs hely elérhető',
				 112 => 'Most olvasd el a 3 fő szabályunkat:',
				 113 => 'Ha látsz valakit akit ismersz, NE hozd nyilvánosságra. Ne pletykálkodj.',
				 114 => 'Ha szexelsz a tagjainkkal, a te felelősséged, hogy megóvd magad a szexuális úton terjedő betegségektől.',
				 115 => 'Tartsd tiszteletben tagjaink szexuális vágyait. A tagjaink egyszerű nők, nem prostituáltak vagy pornószínészek.',
				 116 => 'A szabályok nem betartása azonnali kizárással jár! Ha feltételeinket elfogadod, kattints az "Egyetértek" gombra, hogy továbblépj a regisztrációs oldalra.',
				 117 => 'Szabad helyek keresése...',
				 118 => 'Gratulálunk!',
				 119 => 'Fontos!',
				 120 => 'Mielőtt megmutatnánk a közelben levő, azonnali szexet kereső nők képeit, fel kell tennünk néhány kérdést.',
				 121 => 'Az itt látható nők közül sok egyedülálló anyuka, vagy elhanyagolt feleség, akik vágynak egy kis kalandra. Lehetséges, hogy néhányat közülük ismersz is, sőt, az is lehet, hogy a szomszédod is köztük van. Megígéred, hogy megtartod magadnak ezeknek a nőknek a személyazonosságát?',
				 122 => 'Ezek a nők megkértek minket arra, hogy tiltsuk le azokat a férfiakat, akik "kapcsolatot" keresnek. Ők csak gyors, alkalmi szexre vágynak. Elfogadod a kérésüket?',
				 123 => 'Elmúltál 18 éves? Az oldalon levő nők arra kértek minket, hogy ennél fiatalabb fiúkat ne engedjünk az oldalra, mert éretlenek és tiszteletlenek.',
				 124 => 'Használnál óvszert szex közben a partnereddel, akivel a mi oldalunkon keresztül ismerkedtél meg?',
				 125 => 'Ez NEM hagyományos társkereső oldal!',
				 126 => 'Figyelem!',
				 127 => 'DUGJ MOST',
				 128 => 'Szerezd meg a környéken lakó nők WhatsApp számát és dugj még ma!',
				 129 => 'Küldj SMS-t és kapcsolatba hozunk egy közelben lakó dugópajtással, aki még ma szeretne szexelni!',
				 130 => 'Milyen nővel szeretnél dugni még ma?',
				 131 => 'Milyen távolságra vezetnél el a szexért?',
				 132 => 'Küldj SMS-t és dugj',
				 133 => 'Volt valaha szexuális úton terjedő betegséged?',
				 134 => 'Kilépés',
				 135 => 'Most meztelen képeket fogsz látni nőkről. Arra kérünk, legyél bizalmas.',
				 136 => 'Most már megnézheted a közeledben lévő nők listáját és képeit.',
				 137 => 'Kattints a "Tovább" gombra, hogy befejezd a regisztrációt.',
				 138 => 'Ez a weboldal a szex kapcsolatokról szól. Üzenetet kell küldened, és szexet szervezni.',
				 139 => 'Jelenleg (19) nő van online 10 km-re tőled.',
				 140 => 'Szeretnél továbblépni?',
				 141 => 'Az oldalon szereplő nők arra kértek minket, ne engedjük meg 18 éven aluli fiúknak a regisztrációt, azok illetlen viselkedésére való tekintettel.',
				 142 => 'Tagjaink nagy részéhez hasonlóan téged is csak a szex érdekel?',
				 143 => 'A tagjaink nem akarnak senki olyat, aki kapcsolatban van. Ha kapcsolatot szeretnél, keress fel egy randioldalt.',
				 144 => 'Milyen típusú nők tetszenek?',
				 145 => 'Fiatalok',
				 146 => 'Idősebb',
				 147 => 'Elvált',
				 148 => 'Férjezettek',
				 149 => 'Özvegyek',
				 150 => 'Nagymamák',
				 151 => 'Melyik applikációt használod chatelésre?',
				 152 => 'Átnézzük a válaszaidat.',
				 153 => 'A válaszaid alapján 3 nőt találtunk, aki kész szexelni most azonnal!',
				 154 => 'Regisztrálhatsz az exkluzív weboldalunkra.',
				 155 => 'REGISZTRÁCIÓ férfiaknak rendelkezésre áll még',
				 156 => 'Jobb mint a',


				);

			$_cta = array(	
			/*cta*/
				 1 => 'Hirdetések csak nagykorúak számára elérhetőek. Az eléréshez',
				 2 => 'Küldj SMS-t',
				 3 => 'számra',
				 4 => 'Miután megkaptad a jelszavat a belépéshez,ird be be az alábbi mezőbe:',
				 5 => 'Tovább',
				 6 => 'Ird át a jelszavat a mobilodról',
				 7 => '*Hibás jelszó',

				);

			$_tos = array( 
			/*tos*/
				 1 => 'Minden jog fenntartva. Kizárólag 18 éven felüliek számára. A(z) JO szolgáltatás egy 0690444422 kódon futó csevegőszolgáltatás. Minden elküldött szöveges üzenet ára 409,99 áfával együtt. Szolgáltató: Internet marketing d.o.o, Jovana Dučića 25, 78 000 Banja Luka. Ügyfélszolgálat: 003614554695. Ahhoz, hogy leiratkozzon a szolgáltatásról, küldje el a szolgáltatáshoz kapcsolódó telefonszámát a smsc.hu @ cc-global.info e-mail címre. A felhasználási feltételek megtekintéséhez kattintson',
				 2 => 'ide.',
				 3 => '',
				 4 => 'Affiliate',
				
				 
			);
?>