<?php
			$_defaultNiche = 'nude'; //default niche MUST exists for this country!!!
			$_lang = array(
				 1 => 'Upozorenje',
				 2 => 'Da',
				 3 => 'Ne',
				 4 => 'Dalje',
				 5 => 'Korak',
				 6 => 'Prihvatam',
				 7 => 'OK',
				 8 => 'do',
				 9 => 'Pitanje',
				 10 => 'Ovaj sajt sadrži seksualno eksplicitne slike osoba koje poznaješ.',
				 19 => 'Ove žene traže SAMO povremene partnere za seks.',
				 20 => 'Imaš sreće, registracija za muškarce je otvorena još',
				 21 => 'Molimo te da odgovoriš na nekoliko jednostavnih pitanja, da bismo videli da li na našem sajtu imamo pravu osobu za tebe',
				 22 => 'Hvala.',
				 30 => 'Da li imaš više od 18 godina?',
				 39 => 'Fizički izgled',
				 40 => 'Kakav tip tela te uzbuđuje?',
				 41 => 'Mršavije',
				 42 => 'Normalne',
				 43 => 'Debeljuce',
				 44 => 'Velike sise pod obavezno',
				 45 => 'Velika guzica pod obavezno',
				 46 => 'Tvoj cilj',
				 48 => 'Kakvu vrstu veze tražiš?',
				 49 => 'Molimo da izabereš do 3 odgovora',
				 50 => 'Za jednu noć',
				 51 => 'Seks više puta',
				 52 => 'Redovan seks, ali bez obaveza',
				 53 => 'Ozbiljna veza',
				 54 => 'Brak',
				 55 => 'Željene godine',
				 56 => 'Koje godine ti najbolje odgovaraju?',
				 57 => 'Lokacija',
				 58 => 'Udaljenost između tebe i nje?',
				 59 => '1-5 km daleko od moje trenutne lokacije',
				 60 => 'Isti grad',
				 62 => 'Gradovi u blizini su OK',
				 64 => 'Ista država',
				 65 => 'Nije bitno',
				 70 => 'OK',
				 71 => 'Dalje',
				 72 => 'Slažem se',
				 80 => 'Upiši svoju e-mail adresu da bi nastavio dalje',
				 81 => 'Upiši email',
				 82 => 'Pošalji',
				 90 => 'minuta i',
				 91 => 'sekundi',
				 92 => 'nekoliko sekundi',
				 99 => 'Email verifikacija',
				 100 => 'Rezultat',
				 101 => 'Analiziramo tvoje odgovore',
				 102 => 'Lociramo odgovarajuće seks partnerke',
				 103 => '42 članice u tvojoj blizini',
				 104 => 'Samo 3 slobodna mesta za registraciju',
				 105 => 'Kvalifikovan si da se registruješ!',
				 106 => 'Naša pravila:',
				 109 => 'Prethodne registracije nisu pronađene',
				 110 => 'Trenutno imamo samo',
				 111 => 'slobodna mesta za registraciju',
				 112 => 'Sada pročitaj naša 3 pravila:',
				 113 => 'Ako vidiš nekoga koga poznaješ, NE objavljuj to javno. Ne širi tračeve.',
				 114 => 'Kada imaš seks sa nekom od naših članica, tvoja je odgovornost da se zaštitiš od polno prenosivih bolesti.',
				 115 => 'Poštuj seksualne želje drugih članica. Naši korisnici su normalne žene, a ne prostitutke ili porno zvezde.',
				 116 => 'Nepoštovanje ovih pravila će dovesti do trenutnog ukidanja tvog naloga! Ako se slažeš sa svime iznad napisanim, klikni na dugme "Slažem se" da bi nastavio na stranicu sa registracijom.',
				 117 => 'Tražimo slobodna mesta za registraciju...',
				 118 => 'Čestitamo!',
				 119 => 'Važno!',
				 120 => 'Pre nego što ti pokažemo slike žena koje žive u tvojoj blizini i koje odmah žele seks, moramo da ti postavimo nekoliko pitanja.',
				 121 => 'Mnoge od ovih žena su očajne samohrane majke i udate žene u potrazi za vanbračnom aferom. Moguće je da neke od njih poznaješ, ili čak da su ti komšinice. Da li ćeš identitet ovih žena zadržati za sebe?',
				 122 => 'Ove žene su nas zamolile da blokiramo muškarce koji traže "vezu". One žele jedino brz seks, a ne vezu. Da li se slažeš sa ovim zahtevom?',
				 123 => 'Konačno, da li imaš 18 ili više godina? Žene su tražile da, zbog nepristojnog ponašanja, muškarcima mlađim od 18 godina ne dopustimo pristup.',
				 124 => 'Da li bi prilikom seksa sa partnerkom koju si upoznao na našem sajtu koristio kondom?',
				 125 => 'Ovo NIJE sajt za upoznavanje!',
				 126 => 'Pažnja!',
				 127 => 'JEBI SADA',
				 128 => 'Dobij WhatsApp broj žena iz tvoje okoline i jebi ih danas!',
				 129 => 'Pošalji SMS i spojićemo te sa jebačicama iz tvoje okoline koje žele seks danas!',
				 130 => 'Kakve žene želiš da jebeš danas?',
				 131 => 'Koliko daleko želiš da se voziš radi seksa?',
				 132 => 'Pošalji SMS i jebi!',
				 133 => 'Da li si ikad imao polno prenosivu bolest?',
				 134 => 'Odustani',
				 135 => 'Videćeš fotografije golih žena. Molimo budi diskretan.',
				 136 => 'Sada možeš da pogledaš listu i fotografije žena koje se nalaze blizu tebe.',
				 137 => 'Da bi nastavio na stranicu sa registracijom, klikni na dugme "Dalje".',
				 138 => 'Ova stranica je fokusirana na seks kontakte. Treba da pošalješ poruku i dogovoriš seks',
				 139 => 'Trenutno je (19) žena online u krugu od 10 km od tebe.',
				 140 => 'Da li želiš da nastaviš?',
				 141 => 'Žene su zahtevale da, zbog nepristojnog ponašanja, ne dopustimo pristup muškarcima mlađim od 18 godina.',
				 142 => 'Da li te, kao i naše članice, zanima samo seks?',
				 143 => 'Naše članice ne žele muškarce koji traže vezu. Ako želiš vezu, potraži stranicu za upoznavanje.',
				 144 => 'Kakav tip žene voliš?',
				 145 => 'Mlađe',
				 146 => 'Starije',
				 147 => 'Razvedene',
				 148 => 'Udate',
				 149 => 'Udovice',
				 150 => 'Babe',
				 151 => 'Koju aplikaciju koristis za dopisivanje?',
				 152 => 'Tvoji odgovori su pregledani.',
				 153 => 'Na osnovu tvojih odgovora smo pronašli 3 žene koje su odmah spremne na seks!',
				 154 => 'Možeš da se registruješ na naš ekskluzivni sajt.',
				 155 => 'REGISTRACIJA za muškarce je otvorena još',
				 156 => 'Bolje nego',


				);

			$_cta = array(	
			/*cta*/
				 1 => 'Pristup oglasima je dozvoljen samo punoletnim osobama. Za pristup',
				 2 => 'Pošalji SMS',
				 3 => 'na broj',
				 4 => 'Nakon što primiš lozinku za direktan pristup, prepiši je u polje ispod:',
				 5 => 'Dalje',
				 6 => 'Prepiši lozinku sa svog mobilnog',
				 7 => '*Lozinka neispravna',

				);

			$_tos = array(
			/*tos*/
				 1 => '<span style=" font-size: 22px; font-weight:bold; color:#249600">© Sva prava pridržana. Samo za 18+ Detaljna prava i uslove pogledajte na stranici</span>',
				 2 => '<span style=" font-size: 22px; font-weight:bold; color:#249600">Pravila i uslovi</span>',
				 3 => '<span class="temp" style=" font-size: 22x; font-weight:bold; color:#249600">Cena svakog SMSa ka 1441: MTS: 182,64 Din, Telenor: 183,60 Din, VIP: 183,48 Din</span>',
				 4 => '<span style=" font-size: 22px; font-weight:bold; color:#249600">Affiliate</span>',
			
		
			);
?>