<?php
			$_defaultNiche = 'nude'; //default niche MUST exists for this country!!!
			$_lang = array(
				 1 => 'Upozornenie',
				 2 => 'Áno',
				 3 => 'Nie',
				 4 => 'Ďalej',
				 5 => 'Krok',
				 6 => 'Súhlasím',
				 7 => 'OK',
				 8 => 'do',
				 9 => 'Otázka',
				 10 => 'Táto internetová stránka obsahuje sexuálne explicitné fotky ľudí, ktorých poznáš.',
				 19 => 'Tieto ženy hľadajú IBA partnerov na príležitostný sex.',
				 20 => 'Máš šťastie, registrácia pre mužov je otvorená ďalších',
				 21 => 'Prosíme ťa, aby si odpovedal na niekoľko jednoduchých otázok, aby sme zistili, či máme vhodnú osobu pre teba na našej internetovej stránke',
				 22 => 'Ďakujeme.',
				 30 => 'Máš viac ako 18 rokov?',
				 39 => 'Fyzický vzhľad',
				 40 => 'Aký typ tela ťa vzrušuje?',
				 41 => 'Chudšie',
				 42 => 'Normálne',
				 43 => 'Tučky',
				 44 => 'Veľké prsia sú povinné',
				 45 => 'Veľký zadok je povinný',
				 46 => 'Tvoj cieľ',
				 48 => 'Aký typ vzťahu hľadáš?',
				 49 => 'Prosíme, vyber si maximálne 3 odpovede',
				 50 => 'Na jednu noc',
				 51 => 'Viacnásobný sex',
				 52 => 'Pravidelný sex, ale bez záväzkov',
				 53 => 'Vážny vzťah',
				 54 => 'Manželstvo',
				 55 => 'Požadovaný vek',
				 56 => 'Aký vek ti najviac vyhovuje?',
				 57 => 'Umiestnenie',
				 58 => 'Vzdialenosť medzi tebou a ňou?',
				 59 => '1-5 km od mojej aktuálnej polohy',
				 60 => 'Rovnaké mesto',
				 62 => 'Vyhovujú mi mestá v okolí',
				 64 => 'Rovnaká krajina',
				 65 => 'Je to jedno',
				 70 => 'Ok',
				 71 => 'Ďalej',
				 72 => 'Súhlasím',
				 80 => 'Zadaj svoju e-mailovú adresu, aby si pokračoval',
				 81 => 'Zadaj e-mailovú adresu',
				 82 => 'Odoslať',
				 90 => 'minút a',
				 91 => 'sekúnd',
				 92 => 'niekoľko sekúnd',
				 99 => 'Overenie e-mailovej adresy',
				 100 => 'Výsledok',
				 101 => 'Analyzujeme tvoje odpovede',
				 102 => 'Vyhľadávame vhodné sexuálne partnerky',
				 103 => '42 členiek v tvojom okolí',
				 104 => 'Iba 3 voľné registračné miesta',
				 105 => 'Máš nárok na registráciu!',
				 106 => 'Naše pravidlá:',
				 109 => 'Predchádzajúce registrácie neboli nájdené',
				 110 => 'Momentálne máme len',
				 111 => 'voľných registračných miest',
				 112 => 'Teraz si prečítaj naše 3 pravidlá:',
				 113 => 'NEZVEREJŇUJ, ak uvidíš niekoho, koho poznáš! Nesmieš šíriť klebety.',
				 114 => 'Pri sexe s niektorou našou členkou je tvojou zodpovednosťou chrániť sa pred pohlavnými chorobami.',
				 115 => 'Rešpektuj sexuálne túžby ostatných členiek. Naše členky sú obyčajné ženy, nie sú prostitútky alebo porno hviezdy.',
				 116 => 'Porušenie týchto pravidiel bude mať za následok okamžité zrušenie tvojho účtu. Ak súhlasíš so všetkými pravidlami uvedenými vyššie, klikni na tlačidlo „Súhlasím“ a pokračuj na registračnú stránku.',
				 117 => 'Hľadáme dostupné miesta na registráciu...',
				 118 => 'Gratulujeme!',
				 119 => 'Dôležité!',
				 120 => 'Skôr než ti ukážeme fotky žien, ktoré žijú v tvojom okolí a ktoré chcú okamžite sexovať, musíme ti položiť niekoľko otázok.',
				 121 => 'Mnohé z týchto žien sú zúfalé slobodné matky a vydaté ženy, ktoré hľadajú nemanželskú aféru. Možno, že poznáš niektoré z nich, alebo sú dokonca tvoje susedky. Zachováš identitu týchto žien?',
				 122 => 'Tieto ženy nás poprosili, aby sme zablokovali mužov, ktorí hľadajú "vzťah". Ony chcú iba rýchly sex, nechcú vzťah. Súhlasíš s touto požiadavkou?',
				 123 => 'Máš viac ako 18 rokov? Ženy nás požiadali, aby sme nepovolili prístup mužom mladším ako 18 rokov z dôvodu ich neslušného správania.',
				 124 => 'Použil by si kondóm pri sexe s osobou, s ktorou si sa zoznámil prostredníctvom našej internetovej stránky?',
				 125 => 'Toto NIE JE zoznamka!',
				 126 => 'Pozor!',
				 127 => 'ŠUKAJ TERAZ',
				 128 => 'Získaj WhatsApp čísla žien zo svojho okolia a šukaj dnes!',
				 129 => 'Pošli SMS a spojíme ťa s jebačkami z tvojho okolia, ktoré chcú sexovať dnes!',
				 130 => 'Aké ženy chceš šukať dnes?',
				 131 => 'Ako ďaleko chceš jazdiť kvôli sexu?',
				 132 => 'Pošli SMS a šukaj!',
				 133 => 'Trpel si niekedy pohlavne prenosnou chorobou?',
				 134 => 'Zrušiť',
				 135 => 'Uvidíš fotky nahých žien. Prosíme, buď diskrétny.',
				 136 => 'Teraz si môžeš pozrieť zoznam a fotografie žien z tvojho okolia.',
				 137 => 'Klikni na tlačidlo "Ďalej", aby si pokračoval na registračnú stránku. ',
				 138 => 'Táto stránka je zameraná na sexuálne kontakty. Potrebuješ poslať správu a dohodnúť si sex',
				 139 => 'Momentálne je online (19) žien v okruhu 10 km.',
				 140 => 'Chceš pokračovať?',
				 141 => 'Ženy požiadali, aby sme nedovolili prístup mužom, ktorí majú menej ako 18 rokov, kvôli neslušnému správaniu.',
				 142 => 'Máš záujem iba o sex ako naše členky?',
				 143 => 'Naše členky nechcú mužov, ktorí hľadajú vzťah. Ak chceš vzťah, nájdi zoznamku.',
				 144 => 'Aký typ ženy máš rád?',
				 145 => 'Mladšie',
				 146 => 'Staršie ',
				 147 => 'Rozvedené',
				 148 => 'Vydaté',
				 149 => 'Vdovy',
				 150 => 'Babky',
				 151 => 'Ktoru cetovaciu aplikaciu pouzivas?',
				 152 => 'Tvoje odpovede sú skontrolované.',
				 153 => 'Na základe tvojich odpovedí sme našli 3 ženy, ktoré sú hneď pripravené na sex!',
				 154 => 'Môžeš sa zaregistrovať na našej exkluzívnej stránke.',
				 155 => 'REGISTRÁCIA pre mužov je k dispozícii za',
				 156 => 'Lepšie ako',

				 
				 );

			$_cta = array(	
			/*cta*/
				 1 => 'Prístup k osobným inzerátom je povolený iba pre ľudí vo veku nad 18 rokov. Pre prístup',
				 2 => 'Odošlite SMS',
				 3 => 'na číslo',
				 4 => 'Po prijatí hesla pre priamy prístup ho napíšte do políčka:',
				 5 => 'Ďalej',
				 6 => 'Napíšte heslo zo svojho mobilného telefónu',
				 7 => '* Chybné heslo',

				);

			$_tos = array(
			/*TOS*/
				 1 => '© Podrobné podmienky služby možno nájsť na',
				 2 => 'stránke.',
				 3 => ' Zaslaním SMS si objednáte službu Chat s operátorom určenú pre užívateľov 18 +. Každá odpoveď na zaslanú SMS stojí 1,6 € s DPH. Pre vypnutie služby pošlite TAP STOP na 6678. Poskytovateľ: Internet marketing s.r.o, Jovana Ducicha 25, BH. Info: smsc.sk @ cc-global.info / +421233000028 ',
				 4 => 'Affiliate',
			
			);
?>