<?php
			$_defaultNiche = 'nude'; //default niche MUST exists for this country!!!
			$_lang = array(
				1 => 'Aviso',
				2 => 'Sim',
				3 => 'Não',
				4 => 'Continuar',
				5 => 'Passo',
				6 => 'Aceito',
				7 => 'ok',
				8 => 'a',
				9 => 'Pergunta',
				10 => 'Este site contém fotografias sexualmente explícitas de pessoas que conhece.',
				19 => 'Estas mulheres estão à procura APENAS de parceiros para sexo ocasional.',
				20 => 'Está com sorte, o registo para homens está aberto por mais',
				21 => 'Por favor responda a umas simples questões para verificarmos se é a pessoa certa para o nosso site',
				22 => 'Muito obrigado.',
				30 => 'Tem mais de 18 anos de idade?',
				39 => 'Aparência física',
				40 => 'Que tipo de corpo excita-o?',
				41 => 'Magra',
				42 => 'Normal',
				43 => 'Gorda',
				44 => 'Obrigatório mamas grandes',
				45 => 'Rabo grande obrigatório',
				46 => 'O seu objetivo',
				48 => 'Que tipo de relação está à procura?',
				49 => 'Por favor escolha até 3 respostas',
				50 => 'Apenas uma noite',
				51 => 'Sexo por várias vezes',
				52 => 'Sexo regular, mas sem compromisso',
				53 => 'Relação séria',
				54 => 'Casamento',
				55 => 'Idade desejada',
				56 => 'Que idade é mais adequada para si?',
				57 => 'Localização',
				58 => 'Distância entre você e ela?',
				59 => '1-5 km da minha localização atual',
				60 => 'Mesma cidade',
				62 => 'Cidades próximas está bem',
				64 => 'O mesmo país',
				65 => 'Não interessa',
				70 => 'Ok',
				71 => 'Continuar',
				72 => 'Concordo',
				80 => 'Escreva o seu endereço de email para prosseguir',
				81 => 'Insira email',
				82 => 'Enviar',
				90 => 'minutos e',
				91 => 'segundos',
				92 => 'alguns segundos',
				99 => 'Verificação de email',
				100 => 'O resultado',
				101 => 'A analisar as suas respostas',
				102 => 'Nós localizamos parceiras sexuais apropriadas',
				103 => '42 membros na sua área',
				104 => 'Apenas 3 lugares disponíveis para registo',
				105 => 'Você está elegível para se registar!',
				106 => 'As nossas regras:',
				109 => 'Não foram encontrados registos anteriores',
				110 => 'De momento, só temos',
				111 => 'vagas disponíveis para inscrição',
				112 => 'Agora leia as nossas 3 regras:',
				113 => 'Se vir alguém que conhece, NÃO o publique. Não espalhe coscuvilhices.',
				114 => 'Quando fizer sexo com alguns dos nossos membros é da sua responsabilidade proteger-se de doenças sexualmente transmissíveis.',
				115 => 'Respeite os desejos sexuais de outros membros. Os nossos membros são mulheres normais, não são estrelas pornográficas ou prostitutas.',
				116 => 'Não respeitar estas regras irá implicar o cancelamento imediato da sua conta! Se concordar com todos os termos acima escritos, clique no botão “Concordo” para continuar com o registo.',
				117 => 'A verificar se existem vagas disponíveis para registo...',
				118 => 'Parabéns!',
				119 => 'Urgente!',
				120 => 'Antes de lhe mostrarmos as fotografias das mulheres que vivem na sua área e que querem sexo imediatamente, temos que lhe fazer algumas questões.',
				121 => 'Muitas destas mulheres são mães solteiras desesperadas e mulheres casadas em busca de casos fora do matrimônio. É possível que conheça algumas delas ou que sejam suas vizinhas. Vai manter a identidade delas só para si?',
				122 => 'Estas mulheres pediram-nos para bloquear homens que procuram "relacionamentos". Elas apenas querem sexo rápido, não uma relação. Aceita este requisito?',
				123 => 'Por fim, tem mais de 18 anos? Os membros do sexo feminino pediram-nos que não permitíssemos o acesso a homens com menos de 18 anos devido ao seu comportamento inadequado.',
				124 => 'Usaria preservativo ao ter sexo com uma parceira que conhecesse no nosso site?',
				125 => 'Este NÃO É um sítio de encontros clássico!',
				126 => 'Atenção!',
				127 => 'FODER AGORA',
				128 => 'Obtenha os números WhatsApp de mulheres na sua área e foda-as hoje!',
				129 => 'Envie uma SMS e vamos conectá-lo às ordinárias da sua área que querem sexo hoje!',
				130 => 'Que mulheres quer foder hoje?',
				131 => 'Que distância percorria de carro para ter sexo?',
				132 => 'Enviar SMS e foder!',
				133 => 'Já alguma vez teve uma doença sexualmente transmissível?',
				134 => 'Sair',
				135 => 'Verás fotos de mulheres nuas. Por favor, sê discreto.',
				136 => 'Agora pode ver uma lista e fotografias de mulheres que estão perto de si.',
				137 => 'Clique no botão "Continuar" para prosseguir para a página de registo.',
				138 => 'Este site está focado em contatos sexuais. precisa enviar uma mensagem e organizar o sexo',
				139 => 'No momento, existem 19 mulheres online a 10 km de si.',
				140 => 'Deseja continuar?',
				141 => 'As mulheres pediram-nos para não dar-mos acesso a homens menores de 18 anos, devido a comportamento indecente.',
				142 => 'está interessado apenas em sexo, assim como os nossos membros?',
				143 => 'Nossos membros não querem homens que estejam em um relacionamento. Se quer um relacionamento, procure um site de namoro.',
				144 => 'Qual é o seu tipo de mulher?',
				145 => 'Mais novas',
				146 => 'Mais velhas',
				147 => 'Divorciadas',
				148 => 'Casada',
				149 => 'Viúvas',
				150 => 'Avós',
				151 => 'Qual aplicação usa para enviar mensagens de texto? ',
				152 => 'Suas respostas foram avaliadas.',
				153 => 'Com base nas suas respostas, encontramos 3 mulheres prontas para fazer sexo agora!',
				154 => 'pode se registar-se no nosso site exclusivo.',
				155 => 'REGISTO disponível para homens por',
				156 => 'Melhor do que o',

				 


				
				);
			
			$_tos = array(	
			/*tos*/			  

				 1 => '© 18+ Chat Sms com moderador. Clique ',
				 2 => 'aqui',
				 3 => 'para os termos de serviço. Internet marketing ltd, bh. Custo é de 2,10€/sms. Se pretender não receber mais alertas, envie SAIR para 68639. Apoio ao cliente 7O745O2O1, info.pt @ ccsupport.biz.',				 
			 
			);
			
?>