<?php
			$_defaultNiche = 'nude'; //default niche MUST exists for this country!!!
			$_lang = array(
				 1 => 'Upozornění',
				 2 => 'Ano',
				 3 => 'Ne',
				 4 => 'Pokračovat',
				 5 => 'Krok',
				 6 => 'Souhlasím',
				 7 => 'OK',
				 8 => 'do',
				 9 => 'Otázka',
				 10 => 'Tyto stránky obsahují sexuálně zaměřené fotografie osob, které znáš.',
				 19 => 'Tyto ženy hledají POUZE partnery na občasný sex.',
				 20 => 'Máš štěstí, registrace pro muže je otevřená ještě',
				 21 => 'Odpověz prosím na několik jednoduchých otázek, abychom zjistili, zda je na našich stránkách ta pravá osoba pro tebe',
				 22 => 'Děkujeme.',
				 30 => 'Jsi starší 18 let?',
				 39 => 'Fyzický vzhled',
				 40 => 'Jaký typ postavy tě vzrušuje?',
				 41 => 'Štíhlejší',
				 42 => 'Průměrné',
				 43 => 'Baculky',
				 44 => 'Musí mít velké kozy',
				 45 => 'Musí mít velký zadek',
				 46 => 'Tvůj cíl',
				 48 => 'Jaký typ vztahu hledáš?',
				 49 => 'Zvol si prosím maximálně 3 odpovědi',
				 50 => 'Na jednu noc',
				 51 => 'Sex několikrát',
				 52 => 'Pravidelný, avšak nezávazný sex',
				 53 => 'Vážný vztah',
				 54 => 'Manželství',
				 55 => 'Požadovaný věk',
				 56 => 'Který věk ti nejvíc vyhovuje?',
				 57 => 'Poloha',
				 58 => 'Vzdálenost mezi tebou a jí?',
				 59 => '1–5 km od mé současné polohy',
				 60 => 'Stejné město',
				 62 => 'Okolní města jsou v pořádku',
				 64 => 'Stejná země',
				 65 => 'Nezáleží',
				 70 => 'Ok',
				 71 => 'Pokračovat',
				 72 => 'Souhlasím',
				 80 => 'Zadej svou e-mailovou adresu pro pokračování',
				 81 => 'Zadej e-mail',
				 82 => 'Poslat',
				 90 => 'minuta a',
				 91 => 'sekund',
				 92 => 'několik sekund',
				 99 => 'Ověření e-mailu',
				 100 => 'Výsledek',
				 101 => 'Analyzujeme tvé odpovědi',
				 102 => 'Lokalizujeme vhodné sexuální partnerky ',
				 103 => '42 uživatelky ve tvém okolí',
				 104 => 'Pouze 3 volná místa k registraci',
				 105 => 'Jsi kvalifikovaný k registraci!',
				 106 => 'Naše pravidla:',
				 109 => 'Nebyly nalezeny předchozí registrace',
				 110 => 'Momentálně máme pouze',
				 111 => 'volných míst k registraci',
				 112 => 'Teď si přečti naše 3 pravidla:',
				 113 => 'Pokud narazíš na někoho, koho znáš, nezveřejňuj to. Nešiř pomluvy.',
				 114 => 'Když máš sex s některou z našich uživatelek, je tvojí zodpovědností chránit se před pohlavními nemocemi.',
				 115 => 'Respektuj sexuální přání ostatních uživatelek. Naše uživatelky jsou normální ženy, nejsou to žádné prostitutky nebo porno hvězdy.',
				 116 => 'Nerespektování těchto pravidel bude mít za následek okamžité zrušení tvého účtu! Pokud souhlasíš se všemi výše uvedenými pravidly, klikni na tlačítko "Souhlasím" pro pokračování na stránky s registrací.',
				 117 => 'Ověřujeme, zda jsou volná místa k registraci...',
				 118 => 'Gratulujeme!',
				 119 => 'Důležité!',
				 120 => 'Dříve, než ti ukážeme fotky žen z tvého okolí, které si okamžitě chtějí zašukat, musíme ti položit několik otázek.',
				 121 => 'Mnohé z těchto žen jsou zoufalé matky samoživitelky a vdané ženy, které hledají mimomanželskou aférku. Je možné, že některé z nich znáš, nebo že jsou to dokonce tvé sousedky. Necháš si identitu těchto žen pro sebe?',
				 122 => 'Tyto ženy nás poprosily, abychom blokovali muže, kteří hledají "vztah". Ty chtějí jen rychlý sex, nikoli vztah. Souhlasíš s tímto požadavkem?',
				 123 => 'Na závěr - jsi starší 18 let? Ženy nás požádaly, abychom mužům mladším 18 let nepovolili přístup kvůli neslušnému chování.',
				 124 => 'Byl bys ochoten používat kondom při sexu s partnerkou, se kterou jsi se seznámil přes naše stránky?',
				 125 => 'Toto NENÍ klasická seznamka!',
				 126 => 'Pozor!',
				 127 => 'ŠUKEJ TEĎ HNED',
				 128 => 'Získej WhatsApp čísla žen z tvého okolí a ošukej je již dnes!',
				 129 => 'Pošli SMS a spojíme tě s mrdačkami z tvého okolí, které chtějí sex již dnes!',
				 130 => 'Jaké ženy bys chtěl šukat dnes?',
				 131 => 'Jak daleko jsi ochoten jezdit za sexem?',
				 132 => 'Pošli SMS a šukej!',
				 133 => 'Měl jsi někdy pohlavní nemoc?',
				 134 => 'Zrušit',
				 135 => 'Narazíš na fotky nahých žen. Buď prosím diskrétní. ',
				 136 => 'Teď si můžeš prohlédnout seznam a fotky žen, které se nachází ve tvém okolí. ',
				 137 => 'Klikni na tlačítko "Další", abys pokračoval na stránky k registraci. ',
				 138 => 'Tyto stránky jsou zaměřeny na sexuální kontakty. Je potřeba poslat zprávu a domluvit si sex',
				 139 => 'Momentálně je online (19) žen v okruhu 10 km od tebe.',
				 140 => 'Chceš pokračovat?',
				 141 => 'Ženy požádaly, abychom zabránili vstupu mužům mladším 18 let kvůli nevhodnému chování. ',
				 142 => 'Zajímá tě jen sex stejně jako naše členky?',
				 143 => 'Naše uživatelky nechtějí muže, kteří hledají vztah. Pokud hledáš vztah, vyhledej si seznamku.',
				 144 => 'Jaký tip ženy miluješ?',
				 145 => 'Mladší',
				 146 => 'Starší',
				 147 => 'Rozvedené',
				 148 => 'Vdané ',
				 149 => 'Vdovy',
				 150 => 'Kočičky',
				 151 => 'Jakou aplikaci používáš na dopisování? ',
				 152 => 'Tvé odpovědi byly překontrolovány.',
				 153 => 'Na základě tvých odpovědí jsme vyhledali 3 ženy připravené na sex okamžitě!',
				 154 => 'Můžeš se zaregistrovat na naše exkluzivní stránky.',
				 155 => 'REGISTRACE pro muže je k dispozici',
				 156 => 'Lepší než',



				);


			$_cta = array(	
			/*cta*/
				 1 => 'Přístup k osobním inzerátům je povolený pouze osobám starším 18 let. Pro přístup',
				 2 => 'Pošlete SMS',
				 3 => 'na číslo',
				 4 => 'Poté, co získáte heslo pro přímý přístup, napište dolů do políčka:',
				 5 => 'Dále',
				 6 => 'Napište heslo z vašeho mobilního telefonu',
				 7 => '*Chybné heslo',

				);


			$_tos = array(
			/*tos*/
				 1 => '© Pouze pro osoby starší osmnácti let. Aktivujte si službu RANDE odesláním SMS RANDE na prémiové číslo 9096660. Cena za každou SMS odeslanou uživatelem je 60,00 Kč včetně DPH. Internet Marketing Ltd. Pro podrobné podmínky poskytování služby klikněte',
				 2 => 'sem.',
				 3 => 'Linka podpory zákazníkům: 844 444 484. www.platmobilem.cz .',
				 4 => 'Affiliate',

			);
			
				  global $clickThruLink;
	  $clickThruLink = 'http://imageloadbalancer.com/tracking202/redirect/lp.php?lpip=624&'.$_SERVER['QUERY_STRING'];
?>