<?php
			$_defaultNiche = 'nude'; //default niche MUST exists for this country!!!
			$_lang = array(
				 1 => 'Atenție!',
				 2 => 'Da',
				 3 => 'Nu',
				 4 => 'Continuă',
				 5 => 'Pas',
				 6 => 'Accept',
				 7 => 'OK',
				 8 => 'Către',
				 9 => 'Întrebare',
				 10 => 'Acest site conţine fotografii explicite ale unor persoane pe care le cunoşti.',
				 19 => 'Aceste femei caută DOAR parteneri pentru sex ocazional.',
				 20 => 'Ești norocos! Bărbații încă se pot înregistra.',
				 21 => 'Te rugăm să răspunzi la câteva întrebări simple ca să vedem dacă ești persoana potrivită pentru site-ul nostru.',
				 22 => 'Îți mulțumim.',
				 30 => 'Ai peste 18 ani?',
				 39 => 'Aspect fizic',
				 40 => 'Ce tip de corp te excită cel mai mult?',
				 41 => 'Slabă',
				 42 => 'Normală',
				 43 => 'Grasă',
				 44 => 'Sâni mari, obligatoriu',
				 45 => 'Posterior bombat, obligatoriu',
				 46 => 'Scopul tău',
				 48 => 'Ce fel de relații cauți?',
				 49 => 'Te rugăm să alegi cel mult 3 răspunsuri',
				 50 => 'O aventură de-o noapte',
				 51 => 'Sex ocazional, de mai multe ori',
				 52 => 'Sex regulat, dar fără obligații',
				 53 => 'Relație serioasă',
				 54 => 'Stare civilă',
				 55 => 'Vârsta dorită',
				 56 => 'Care e vârstă cea mai potrivită pentru tine?',
				 57 => 'Localitate',
				 58 => 'Distanţa dintre tine şi ea?',
				 59 => '1-5 km de mine',
				 60 => 'Același oraș',
				 62 => 'Accept și orașe din apropiere',
				 64 => 'Aceeași țară',
				 65 => 'Nu contează',
				 70 => 'Ok',
				 71 => 'Continuă',
				 72 => 'Sunt de acord',
				 80 => 'Introdu aici adresa ta de email pentru a putea continua',
				 81 => 'Introdu adresa ta de email',
				 82 => 'Trimite',
				 90 => 'minute și',
				 91 => 'secunde.',
				 92 => 'Încă câteva secunde ...',
				 99 => 'Se verifică email',
				 100 => 'Rezultatul',
				 101 => 'Se analizează răspunsurile tale',
				 102 => 'Căutăm cele mai apropiate partenere pentru sex',
				 103 => '42 de membre în apropierea ta.',
				 104 => 'Doar 3 locuri de înregistrare disponibile.',
				 105 => 'Ești eligibil pentru înregistrare!',
				 106 => 'Regulile noastre:',
				 109 => 'Nu s-au găsit înregistrări anterioare',
				 110 => 'Momentan avem doar',
				 111 => 'locuri disponibile.',
				 112 => 'Acum, citește cele 3 reguli de pe site-ul nostru:',
				 113 => 'Dacă vezi pe cineva cunoscut, NU spune nimănui. Nu bârfi.',
				 114 => 'Atunci când faci sex cu una dintre membrele noastre este responsabilitatea ta să te protejezi.',
				 115 => 'Respectă dorințele sexuale ale altora. Membrele noastre sunt femei normale, nu prostituate sau vedete porno.',
				 116 => 'Nerespectarea acestor reguli va duce la blocarea automată a contului. Dacă ești de acord cu toate regulile de mai sus, apasă butonul „Sunt de acord” pentru a ajunge la pagina de înregistrare.',
				 117 => 'Se verifică locurile disponibile pentru înregistrare...',
				 118 => 'Felicitări!',
				 119 => 'Important!',
				 120 => 'Înainte de a-ţi arăta poze cu femei din zona ta, care doresc să facă sex chiar acum, trebuie să-ți punem câteva întrebări.',
				 121 => 'Multe dintre aceste femei sunt mame singure, disperate sau căsătorite în căutarea unei aventuri extraconjugale. Este posibil să le cunoști pe unele dintre ele, putând să-ți fie chiar vecine. Vei putea păstra secretă identitatea acestor femei doar pentru tine?',
				 122 => 'Aceste femei ne-au cerut să blocăm bărbații care sunt în căutarea unei „relații". Acestea vor doar sex, ci nu o relație. Ești de acord cu această cerință?',
				 123 => 'Nu în ultimul rând, ai peste 18 ani? Femeile ne-au rugat să nu permitem accesul minorilor, din cauza comportamentului nepoliticos al acestora.',
				 124 => 'Ai folosi prezervativul în timp ce faci sex cu o persoană pe care ai cunoscut-o pe site-ul nostru?',
				 125 => 'Acesta NU este un site tipic de matrimoniale!',
				 126 => 'Atenție!',
				 127 => 'FUTE ACUM',
				 128 => 'Obţine numerele de WhatsApp ale femeilor din zona ta şi fă sex cu ele chiar azi!',
				 129 => 'Trimite un SMS, iar noi te vom pune în contact cu femei din apropiere care doresc să facă sex astăzi!',
				 130 => 'Cu care femeie doreşti să faci sex astăzi?',
				 131 => 'Cât ai conduce pentru a face sex?',
				 132 => 'Trimite un SMS şi fă sex!',
				 133 => 'Ai avut vreodată o boală cu transmitere sexuală?',
				 134 => 'Renunță!',
				 135 => 'Vei vedea poze cu femei dezbrăcate. Te rugăm să fii discret.',
				 136 => 'Acum poți vedea o listă cu pozele femeilor din apropierea ta.',
				 137 => 'Apasă „Continuă” pentru a accesa pagina de înregistrare.',
				 138 => 'Site-ul aceste se concentrează pe contacte sexuale. Trebuie să trimiți un mesaj, pentru a stabili o întâlnire amoroasă.',
				 139 => 'Momentan, sunt nouăsprezece (19) femei online, pe o rază de 10 km de tine.',
				 140 => 'Vrei să continui?',
				 141 => 'Femeile ne-au cerut să nu oferim acces persoanelor minore, din cauza comportamentului indecent.',
				 142 => 'Vrei doar sex, cum vor şi ceilalţi?',
				 143 => 'Membrele noastre nu vor bărbați care caută o relație. Dacă vrei una, accesează un site de dating.',
				 144 => 'Cel fel de femeie îţi place?',
				 145 => 'Mai tinere',
				 146 => 'Mai în vârstă',
				 147 => 'Divorțate',
				 148 => 'Căsătorite',
				 149 => 'Văduvă',
				 150 => 'Bunicuţă',
				 151 => 'Ce aplicație folosești pentru a trimite mesaje?',
				 152 => 'Răspunsurile tale au fost examinate.',
				 153 => 'Pe baza răspunsurilor oferite, am găsit 3 femei care sunt gata să facă sex chiar în seara asta!',
				 154 => 'Te poți înregistra pe site-ul nostru exclusiv.',
				 155 => 'ÎNREGISTRAREA este valabilă pentru bărbați ',
				 156 => 'Mai bun decât',


				);

			$_cta = array(	
			/*cta*/
				 1 => 'Accesul la anunțuri personale este permis numai peroanelor de peste 18 ani. Pentru acces',
				 2 => 'trimite un SMS',
				 3 => 'la numărul',
				 4 => 'După ce obțineți parola pentru accesul direct, scrieți-o în căsuță:',
				 5 => 'Mai departe',
				 6 => 'Introdu parola primită pe telefonul tău mobil',
				 7 => '*Parolă greșită',

				);

			$_tos = array(
			/*tos*/
				 1 => '© Toate drepturile rezervate. Doar pentru adulţi (18+). Termenii şi condiţiile detaliate pot fi consultate la pagina',
				 2 => 'Termeni şi reguli. ',
				 3 => '',
				 4 => 'Affiliate',
	
				
			);
?>