<?php
			$_defaultNiche = 'nude'; //default niche MUST exists for this country!!!
			$_lang = array(
				 1 => 'Upozorenje',
				 2 => 'Da',
				 3 => 'Ne',
				 4 => 'Dalje',
				 5 => 'Korak',
				 6 => 'Prihvaćam',
				 7 => 'OK',
				 8 => 'do',
				 9 => 'Pitanje',
				 10 => 'Ova stranica sadrži seksualno eksplicitne slike osoba koje poznaješ.',
				 19 => 'Ove žene traže SAMO povremene partnere za seks.',
				 20 => 'Imaš sreće, registracija za muškarce je otvorena još',
				 21 => 'Molimo te da odgovoriš na nekoliko jednostavnih pitanja da vidimo imamo li pravu osobu za tebe na našoj stranici',
				 22 => 'Hvala.',
				 30 => 'Imaš li više od 18 godina?',
				 39 => 'Fizički izgled',
				 40 => 'Kakav tip tijela te uzbuđuje?',
				 41 => 'Mršavije',
				 42 => 'Normalne',
				 43 => 'Debeljuce',
				 44 => 'Velike sise pod obavezno',
				 45 => 'Velika guzica pod obavezno',
				 46 => 'Tvoj cilj',
				 48 => 'Kakvu vrstu veze tražiš?',
				 49 => 'Molimo, izaberi do 3 odgovora',
				 50 => 'Za jednu noć',
				 51 => 'Seks više puta',
				 52 => 'Redovit seks, ali bez obaveza',
				 53 => 'Ozbiljna veza',
				 54 => 'Brak',
				 55 => 'Željene godine',
				 56 => 'Koje godine ti najbolje odgovaraju?',
				 57 => 'Lokacija',
				 58 => 'Udaljenost između tebe i nje?',
				 59 => '1-5 km od moje trenutačne lokacije',
				 60 => 'Isti grad',
				 62 => 'Gradovi u blizini su U REDU',
				 64 => 'Ista država',
				 65 => 'Nije bitno',
				 70 => 'U redu',
				 71 => 'Dalje',
				 72 => 'Slažem se',
				 80 => 'Upiši svoju e-mail adresu kako bi nastavio dalje',
				 81 => 'Upiši e-mail',
				 82 => 'Pošalji',
				 90 => 'minuta i',
				 91 => 'sekundi',
				 92 => 'nekoliko sekundi',
				 99 => 'Potvrda e-maila',
				 100 => 'Rezultat',
				 101 => 'Analiziramo tvoje odgovore',
				 102 => 'Lociramo odgovarajuće seks partnerice',
				 103 => '42 članice u tvojoj blizini',
				 104 => 'Samo 3 slobodna mjesta za registraciju',
				 105 => 'Kvalificiran si za registraciju!',
				 106 => 'Naša pravila:',
				 109 => 'Prethodne registracije nisu pronađene',
				 110 => 'Trenutno imamo samo',
				 111 => 'slobodna mjesta za registraciju',
				 112 => 'Sada pročitaj naša 3 pravila:',
				 113 => 'Ako vidiš nekoga koga poznaješ, NE objavljuj to javno. Ne širi tračeve.',
				 114 => 'Kada se seksaš s nekom od naših članica, tvoja je odgovornost da se zaštitiš od spolno prenosivih bolesti.',
				 115 => 'Poštuj seksualne želje drugih članova. Naše korisnice su obične žene, ne prostitutke ili porno zvijezde.',
				 116 => 'Nepoštivanje ovih pravila dovest će do trenutačnog ukidanja tvog korisničkog računa! Ako se slažeš sa svime iznad napisanim, klikni na gumb "Slažem se" za nastavak na stranicu za registraciju.',
				 117 => 'Tražimo slobodna mjesta za registraciju...',
				 118 => 'Čestitamo!',
				 119 => 'Važno!',
				 120 => 'Prije nego što ti pokažemo slike žena koje žive u tvojoj blizini i koje odmah žele seks, moramo ti postaviti nekoliko pitanja.',
				 121 => 'Mnoge od ovih žena su očajne samohrane majke i udane žene u potrazi za izvanbračnom aferom. Moguće je da neke od njih poznaješ ili da su ti čak susjede. Hoćeš li zadržati identitet ovih žena za sebe?',
				 122 => 'Ove žene su nas zamolile da blokiramo muškarce koji traže "vezu". One žele samo brzi seks, a ne vezu. Slažeš li se s ovim zahtjevom?',
				 123 => 'Na kraju, imaš li 18 ili više godina? Žene su zatražile da ne dopustimo pristup muškarcima mlađim od 18 godina zbog nepristojnog ponašanja.',
				 124 => 'Hoćeš li koristiti kondom prilikom seksa s partnericom koju si upoznao na našoj stranici?',
				 125 => 'Ovo NIJE stranica za upoznavanje!',
				 126 => 'Pažnja!',
				 127 => 'JEBI SADA',
				 128 => 'Dobij WhatsApp brojeve žena iz svoje okoline i jebi ih danas!',
				 129 => 'Pošalji SMS i spojit ćemo te s jebačicama iz tvoje okoline koje žele seks danas!',
				 130 => 'Kakve žene želiš jebati danas?',
				 131 => 'Koliko se daleko želiš voziti za seks?',
				 132 => 'Pošalji SMS i jebi!',
				 133 => 'Jesi li ikad imao spolno prenosivu bolest?',
				 134 => 'Odustani',
				 135 => 'Vidjet ćeš slike golih žena. Molimo budi diskretan.',
				 136 => 'Sada možeš pogledati popis i slike žena koje se nalaze blizu tebe.',
				 137 => 'Klikni na gumb "Dalje" za nastavak na stranicu s registracijom.',
				 138 => 'Ova stranica se fokusira na seks kontakte. Trebaš poslati poruku i dogovoriti seks',
				 139 => 'Trenutno je (19) žena u krugu od 10 km od tebe na mreži.',
				 140 => 'Želiš li nastaviti?',
				 141 => 'Žene su zatražile da ne dopustimo pristup muškarcima mlađim od 18 godina, zbog nepristojnog ponašanja.',
				 142 => 'Zanima li te samo seks kao i naše članice?',
				 143 => 'Naše članice ne žele muškarce koji treže vezu. Ako želiš vezu, potraži stranicu za upoznavanje.',
				 144 => 'Kakav tip žene voliš?',
				 145 => 'Mlađe',
				 146 => 'Starije',
				 147 => 'Razvedene',
				 148 => 'Udane',
				 149 => 'Udovice',
				 150 => 'Babe',
				 151 => 'Koju aplikaciju koristiš za dopisivanje?',
				 152 => 'Tvoji odgovori su pregledani.',
				 153 => 'Na temelju tvojih odgovora pronašli smo 3 žene koje su spremne na seks odmah!',
				 154 => 'Možeš se registrirati na našu ekskluzivnu stranicu.',
				 155 => 'REGISTRACIJA za muškarce je otvorena još',
				 156 => 'Bolje nego',

				
			);

			$_cta = array(	
			/*cta*/
				 1 => 'Pristup oglasima je dozvoljen samo punoljetnim osobama. Za pristup',
				 2 => 'Pošalji SMS',
				 3 => 'na broj',
				 4 => 'Nakon što primiš zaporku za direktan pristup, prepiši je u polje ispod:',
				 5 => 'Dalje',
				 6 => 'Prepiši zaporku sa svojeg mobitela',
				 7 => '*Zaporka netočna',

				);


			$_tos = array(	
			/*tos*/
				 1 => '© Sva prava pridržana. Samo za 18+ Detaljna prava i uvjete pogledajte na stranici',
				 2 => 'Pravila i uvjeti',
				 3 => '. Cijena poruke sa mobilnog telefona: 6.20 Kn za sve mreže u HR.Cijena inicijalnog SMS-a zavisi od mobilnog providera. Tehnička podrška: Telekomunikacijske usluge d.o.o., Međimurska 28, 42 000 Varaždin, MB: 070096612, OIB 12385860076, Tel: 0038542500871. Sva prava pridržana.',
				 4 => 'Affiliate',
				
				

			);
?>